/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.DashboardController;
import Model.DashboardData;
import javax.swing.JOptionPane;

/**
 *
 * @author Geeshanu Gayan
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadDashboardData();
    }

    private void loadDashboardData() {
    DashboardController controller = new DashboardController();
    DashboardData data = controller.getDashboardData();

    // Update labels with fetched data
    totalIncome.setText("Total Income: Rs." + data.getTotalIncome());
    totalJourneys.setText("Total Journeys: " + data.getTotalJourneys());
    pendingReservations.setText("Total Reservations: " + data.getTotalReservations());

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountBtn = new javax.swing.JButton();
        journeyBtn = new javax.swing.JButton();
        reserveBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();
        incomeBtn = new javax.swing.JButton();
        refundBtn = new javax.swing.JButton();
        contactBtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pendingReservations = new javax.swing.JLabel();
        totalIncome = new javax.swing.JLabel();
        totalJourneys = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountBtn.setBackground(new java.awt.Color(16, 16, 16));
        accountBtn.setBorder(null);
        accountBtn.setContentAreaFilled(false);
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });
        jPanel1.add(accountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 20, 20));

        journeyBtn.setBackground(new java.awt.Color(16, 16, 16));
        journeyBtn.setBorder(null);
        journeyBtn.setContentAreaFilled(false);
        journeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journeyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(journeyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 20, 20));

        reserveBtn.setBackground(new java.awt.Color(16, 16, 16));
        reserveBtn.setBorder(null);
        reserveBtn.setContentAreaFilled(false);
        reserveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(reserveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 30, 20));

        feedbackBtn.setBackground(new java.awt.Color(16, 16, 16));
        feedbackBtn.setBorder(null);
        feedbackBtn.setContentAreaFilled(false);
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(feedbackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 30, 30));

        incomeBtn.setBackground(new java.awt.Color(16, 16, 16));
        incomeBtn.setText("jButton1");
        incomeBtn.setBorder(null);
        incomeBtn.setContentAreaFilled(false);
        incomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(incomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 30, -1));

        refundBtn.setBackground(new java.awt.Color(16, 16, 16));
        refundBtn.setBorder(null);
        refundBtn.setContentAreaFilled(false);
        refundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(refundBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 30, 30));

        contactBtn.setBackground(new java.awt.Color(16, 16, 16));
        contactBtn.setBorder(null);
        contactBtn.setContentAreaFilled(false);
        contactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBtnActionPerformed(evt);
            }
        });
        jPanel1.add(contactBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 30, 20));

        Logoutbtn.setBackground(new java.awt.Color(16, 16, 16));
        Logoutbtn.setBorder(null);
        Logoutbtn.setContentAreaFilled(false);
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 5, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Administrator");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/user (1).png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 760, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingReservations.setBackground(new java.awt.Color(102, 0, 102));
        pendingReservations.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pendingReservations.setText("Pending Reservations");
        pendingReservations.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(pendingReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, -1));

        totalIncome.setBackground(new java.awt.Color(102, 0, 102));
        totalIncome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalIncome.setText("Total Income");
        totalIncome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        totalIncome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(totalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 290, 40));

        totalJourneys.setBackground(new java.awt.Color(102, 0, 102));
        totalJourneys.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalJourneys.setText("Total Journeys");
        totalJourneys.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(totalJourneys, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/salary10.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/booking (1).png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/destination.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 750, 490));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Black and White Modern Login and Sign-up Website Page UI Desktop Prototype.png"))); // NOI18N
        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 970, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
    // Open the UserView page
    UserView account = new UserView();
    account.setVisible(true); // Show the UserView JFrame
    this.dispose(); // Close the current JFrame
    }//GEN-LAST:event_accountBtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
       int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", 
        "Logout Confirmation", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Open the Login page
        View.AdminLogin login = new View.AdminLogin();
        login.setVisible(true);

        // Close the current JFrame
        this.dispose(); 
    }
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void journeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journeyBtnActionPerformed
        // TODO add your handling code here:
    JourneyView journey = new JourneyView();
    journey.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_journeyBtnActionPerformed

    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBtnActionPerformed
        // TODO add your handling code here:
        ReservationView reservation = new ReservationView();
        reservation.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_reserveBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        // TODO add your handling code here:
        FeedbackView feedback = new FeedbackView();
        feedback.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void incomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeBtnActionPerformed
        // TODO add your handling code here:
        PaymentView payment = new PaymentView();
        payment.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_incomeBtnActionPerformed

    private void refundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundBtnActionPerformed
        // TODO add your handling code here:
        RefundView refund = new RefundView();
        refund.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_refundBtnActionPerformed

    private void contactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBtnActionPerformed
        // TODO add your handling code here:
        ContactUsView contact = new ContactUsView();
        contact.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_contactBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton contactBtn;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JButton incomeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton journeyBtn;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel pendingReservations;
    private javax.swing.JButton refundBtn;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JLabel totalIncome;
    private javax.swing.JLabel totalJourneys;
    // End of variables declaration//GEN-END:variables

    
}
