package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Controller.JourneyController;
import Model.Journey;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;


public class JourneyView extends javax.swing.JFrame {
    
   private JourneyController journeyController;
   private JScrollPane scrollPane;
   private DefaultTableModel tableModel;

    public JourneyView() {
    initComponents();
    tableModel = (DefaultTableModel) JourneyTable.getModel();
    jPanel1.setLayout(null); // Explicitly set layout to null
    setupTableModel();
    
    // Initialize the controller
    journeyController = new JourneyController();
    
    addJourneys();

    
}
    
    private void setupTableModel() {
        tableModel.setColumnIdentifiers(new String[]{
            "Journey ID", "Route", "Departure Time","Arrivel Time","Status", "Conductor ID", "Fee"
        });
    }
    
    private void addJourneys(){
    DefaultTableModel model = (DefaultTableModel) JourneyTable.getModel();
    List<Journey> journeys = JourneyController.getAllJourneys();
    model.setRowCount(0);

    for (Journey journey : journeys) {
        Vector<Object> row = new Vector<>();
        row.add(journey.getJourneyId());
        row.add(journey.getRoute());
        row.add(journey.getDepartureTime());
        row.add(journey.getArrivalTime());

        // Print the journey status
        System.out.println("Journey ID: " + journey.getJourneyId() + " Status: " + journey.getStatus());

        row.add(journey.getStatus()); 
        row.add(journey.getConductorId());
        row.add(journey.getFee());
        model.addRow(row);  
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        approveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        logoutBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JourneyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approveBtn.setBackground(new java.awt.Color(51, 102, 0));
        approveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(255, 255, 255));
        approveBtn.setText("Approve");
        approveBtn.setBorder(null);
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(approveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 80, 40));

        cancelBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Reject");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 80, 40));

        backBtn1.setBorder(null);
        backBtn1.setContentAreaFilled(false);
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 20, 30));

        logoutBtn1.setBorder(null);
        logoutBtn1.setContentAreaFilled(false);
        logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 20, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Journey Management");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 370, 50));

        JourneyTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JourneyTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JourneyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "journey_id", "route", "departure_time", "arrivel_time", "status", "conductor_id", "fee"
            }
        ));
        jScrollPane1.setViewportView(JourneyTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 890, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/journey.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 950, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int selectedRow = JourneyTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a journey to reject.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int journeyId = (int) JourneyTable.getValueAt(selectedRow, 0);
        boolean success = journeyController.updateJourneyStatus(journeyId, "cancelled");

        if (success) {
            // Refresh the table
            journeyController.loadJourneysIntoTable(JourneyTable);
            JOptionPane.showMessageDialog(this, "Journey rejected successfully.",
                "Rejection Successful", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to reject journey.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = JourneyTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a journey to approve.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int journeyId = (int) JourneyTable.getValueAt(selectedRow, 0);
        boolean success = journeyController.updateJourneyStatus(journeyId, "scheduled");

        if (success) {
            // Refresh the table
            journeyController.loadJourneysIntoTable(JourneyTable);
            JOptionPane.showMessageDialog(this, "Journey approved successfully.",
                "Approved Successful", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to approved journey.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            this.dispose(); // Close the current window
            AdminLogin loginView = new AdminLogin(); // Open the login screen
            loginView.setVisible(true);
        }
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JourneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JourneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JourneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JourneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
    /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JourneyView().setVisible(true);
        });

            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JourneyTable;
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn1;
    // End of variables declaration//GEN-END:variables

}