/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ReservationController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Model.Reservation;
import java.util.List;
import java.util.Vector;
/**
 *
 * @author Geeshanu Gayan
 */
public class ReservationView extends javax.swing.JFrame {
   private ReservationController reservationController;
   private JScrollPane scrollPane;
   private DefaultTableModel tableModel;

    
   public ReservationView() {
    initComponents();
    
    // Initialize the table model before using it
    tableModel = (DefaultTableModel) reservationTable.getModel(); 
    
    // Initialize the controller
    reservationController = new ReservationController();
    
    setupTableModel();
    addReservations();
}

    private void setupTableModel() {
        tableModel.setColumnIdentifiers(new String[]{
    "Reservation ID", "User ID", "Journey ID", "Seats", "Payment Status", "Created At"
});

    }
    
    private void addReservations(){
        DefaultTableModel model = (DefaultTableModel) reservationTable.getModel();
        
        List<Reservation> reservations = ReservationController.getAllReservations();
        model.setRowCount(0);
    
        for (Reservation reservation : reservations) {
            Vector<Object> row = new Vector<>();
            row.add(reservation.getReservationId());
             row.add(reservation.getUserId());
            row.add(reservation.getJourneyId());
            row.add(reservation.getSeatNumber());
            row.add(reservation.getPaymentStatus());
            row.add(reservation.getCreatedAt());
            model.addRow(row);
        }
    }
    
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn3 = new javax.swing.JButton();
        loutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        clearBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn3.setBorder(null);
        backBtn3.setContentAreaFilled(false);
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 30, 20));

        loutBtn.setBorder(null);
        loutBtn.setContentAreaFilled(false);
        loutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 20, 20));

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reservationid", "userid", "journeyid", "seats", "payment_status", "created_at"
            }
        ));
        jScrollPane1.setViewportView(reservationTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 860, -1));

        clearBtn1.setBackground(new java.awt.Color(204, 0, 102));
        clearBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn1.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn1.setText("Clear");
        clearBtn1.setBorder(null);
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/reservations.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        // TODO add your handling code here:
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void loutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutBtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            this.dispose(); // Close the current window
            AdminLogin loginView = new AdminLogin(); // Open the login screen
            loginView.setVisible(true);
        }
    }//GEN-LAST:event_loutBtnActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        // TODO add your handling code here:
         tableModel.setRowCount(0);
    }//GEN-LAST:event_clearBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       java.awt.EventQueue.invokeLater(() -> {
            new ReservationView().setVisible(true);
        });
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loutBtn;
    private javax.swing.JTable reservationTable;
    // End of variables declaration//GEN-END:variables
}
