/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;

import Model.User;
import Controller.UserController;
import javax.swing.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Geeshanu Gayan
 */
public class UserView extends javax.swing.JFrame {
     private DefaultTableModel tableModel;

    /**
     * Creates new form Accounts
     */
    public UserView() {
    initComponents();
    setLocationRelativeTo(null);

    // Initialize tableModel from the JTable before using it
    tableModel = (DefaultTableModel) uTable.getModel();

    setupTableModel();
    loadUsers();
}

    private void setupTableModel() {
        tableModel.setColumnIdentifiers(new String[]{
            "User ID", "First Name", "Last Name"
        });
    }
    
     private void loadUsers() {
        List<User> users = UserController.getAllUsers();
        DefaultTableModel model = (DefaultTableModel) uTable.getModel();
        model.setRowCount(0); // Clear existing data
        for (User user : users) {
            model.addRow(new Object[]{
                user.getId(),
                user.getFname(),
                user.getLname(),
                user.getUsername(),
                user.getContact(),
                user.getRole()
            });
        }
    }

    private boolean validateInputs() {
        if ( fnameInput.getText().isEmpty() || lnameInput.getText().isEmpty() ||
            lnameInput.getText().isEmpty() || UsernameInput.getText().isEmpty() || passwordInput.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void clearFields() {
        userIdInput.setText("");
        fnameInput.setText("");
        lnameInput.setText("");
        UsernameInput.setText("");
        contactInput.setText("");
        passwordInput.setText("");
        roleGroup.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        roleGroup = new javax.swing.ButtonGroup();
        userIdInput = new javax.swing.JTextField();
        fnameInput = new javax.swing.JTextField();
        lnameInput = new javax.swing.JTextField();
        contactInput = new javax.swing.JTextField();
        UsernameInput = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        findBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        uTable = new javax.swing.JTable();
        passengerOp = new javax.swing.JRadioButton();
        conductorOp = new javax.swing.JRadioButton();
        userLbl = new javax.swing.JLabel();
        fnameLbl = new javax.swing.JLabel();
        lnameLbl = new javax.swing.JLabel();
        contactLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/7124045_logout_icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIdInput.setBackground(new java.awt.Color(204, 204, 204));
        userIdInput.setBorder(null);
        userIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdInputActionPerformed(evt);
            }
        });
        getContentPane().add(userIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 330, 30));

        fnameInput.setBackground(new java.awt.Color(204, 204, 204));
        fnameInput.setBorder(null);
        fnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameInputActionPerformed(evt);
            }
        });
        getContentPane().add(fnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 330, 30));

        lnameInput.setBackground(new java.awt.Color(204, 204, 204));
        lnameInput.setBorder(null);
        getContentPane().add(lnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 330, 30));

        contactInput.setBackground(new java.awt.Color(204, 204, 204));
        contactInput.setBorder(null);
        contactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactInputActionPerformed(evt);
            }
        });
        getContentPane().add(contactInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 330, 30));

        UsernameInput.setBackground(new java.awt.Color(204, 204, 204));
        UsernameInput.setBorder(null);
        getContentPane().add(UsernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 330, 30));

        insertBtn.setBackground(new java.awt.Color(102, 0, 51));
        insertBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Add");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(insertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, 30));

        removeBtn.setBackground(new java.awt.Color(255, 51, 51));
        removeBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("Delete");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, 30));

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, 30));

        findBtn.setBackground(new java.awt.Color(0, 153, 102));
        findBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findBtn.setForeground(new java.awt.Color(255, 255, 255));
        findBtn.setText("Search");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });
        getContentPane().add(findBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, 30));

        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 20, 20));

        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 20, 20));

        passwordInput.setBackground(new java.awt.Color(204, 204, 204));
        passwordInput.setBorder(null);
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 330, 30));

        clearBtn.setBackground(new java.awt.Color(204, 51, 255));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, 30));

        uTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userid", "firstname", "lastname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(uTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 310, 280));

        passengerOp.setBackground(new java.awt.Color(255, 255, 204));
        roleGroup.add(passengerOp);
        passengerOp.setText("Passenger");
        passengerOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerOpActionPerformed(evt);
            }
        });
        getContentPane().add(passengerOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        conductorOp.setBackground(new java.awt.Color(255, 255, 204));
        roleGroup.add(conductorOp);
        conductorOp.setText("Conductor");
        getContentPane().add(conductorOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        userLbl.setBackground(new java.awt.Color(255, 255, 255));
        userLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userLbl.setText("User ID");
        userLbl.setOpaque(true);
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 40));

        fnameLbl.setBackground(new java.awt.Color(255, 255, 255));
        fnameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnameLbl.setText("First Name");
        fnameLbl.setOpaque(true);
        getContentPane().add(fnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 40));

        lnameLbl.setBackground(new java.awt.Color(255, 255, 255));
        lnameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lnameLbl.setText("Last name ");
        lnameLbl.setOpaque(true);
        getContentPane().add(lnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, 30));

        contactLbl.setBackground(new java.awt.Color(255, 255, 255));
        contactLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contactLbl.setText("Contact No");
        contactLbl.setOpaque(true);
        getContentPane().add(contactLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 30));

        userNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        userNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLbl.setText("Username");
        userNameLbl.setOpaque(true);
        getContentPane().add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 30));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 20));

        passwordLbl.setBackground(new java.awt.Color(255, 255, 255));
        passwordLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLbl.setText("Password");
        passwordLbl.setOpaque(true);
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 100, 30));

        roleLbl.setBackground(new java.awt.Color(255, 255, 255));
        roleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roleLbl.setText("Role");
        roleLbl.setOpaque(true);
        getContentPane().add(roleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 30));

        usernameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/acc.png"))); // NOI18N
        getContentPane().add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdInputActionPerformed

    private void contactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactInputActionPerformed

    private void fnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameInputActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here: 
       if (!validateInputs()) {
            return;
        }

        String fname = fnameInput.getText();
        String lname = lnameInput.getText();
        String username = UsernameInput.getText();
        String password = new String(passwordInput.getPassword());
        int contact = Integer.parseInt(contactInput.getText());
        String role = passengerOp.isSelected() ? "Passenger" : "Conductor";

        User user = new User(fname, lname, username, password, contact, role);
        if (UserController.addUser(user)) {
            JOptionPane.showMessageDialog(this, "User added successfully!");
            loadUsers();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add user.");
        }

    }//GEN-LAST:event_insertBtnActionPerformed

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
        
        String userIdText = userIdInput.getText();
        if (userIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a User ID.");
            return;
        }

        int userId = Integer.parseInt(userIdText);
        User user = UserController.findUserById(userId);
        if (user != null) {
            fnameInput.setText(user.getFname());
            lnameInput.setText(user.getLname());
            UsernameInput.setText(user.getUsername());
            contactInput.setText(String.valueOf(user.getContact()));
            passwordInput.setText(user.getPassword());
            if ("Passenger".equals(user.getRole())) {
                passengerOp.setSelected(true);
            } else {
                conductorOp.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "User not found.");
        }
      
    }//GEN-LAST:event_findBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_backBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            this.dispose(); // Close the current window
            AdminLogin loginView = new AdminLogin(); // Open the login screen
            loginView.setVisible(true);
        }

    }//GEN-LAST:event_logoutBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
       String userIdText = userIdInput.getText();
        if (userIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a User ID.");
            return;
        }

        int userId = Integer.parseInt(userIdText);
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (UserController.deleteUser(userId)) {
                JOptionPane.showMessageDialog(this, "User deleted successfully!");
                loadUsers();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete user.");
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (!validateInputs()) {
            return;
        }

        int userId = Integer.parseInt(userIdInput.getText());
        String fname = fnameInput.getText();
        String lname = lnameInput.getText();
        String username = UsernameInput.getText();
        String password = new String(passwordInput.getPassword());
        int contact = Integer.parseInt(contactInput.getText());
        String role = passengerOp.isSelected() ? "Passenger" : "Conductor";

        User user = new User(userId, fname, lname, username, password, contact, role);
        if (UserController.updateUser(user)) {
            JOptionPane.showMessageDialog(this, "User updated successfully!");
            loadUsers();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update user.");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();// Call the existing clearFields method
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void passengerOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerOpActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JRadioButton conductorOp;
    private javax.swing.JTextField contactInput;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JButton findBtn;
    private javax.swing.JTextField fnameInput;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameInput;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JRadioButton passengerOp;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton removeBtn;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JTable uTable;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userIdInput;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables

}